name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: "3.19.3"
          channel: 'stable'

      - name: Run Test
        run: flutter test